# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testing_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "testing_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15testing_service.proto\x12\x07testing"\'\n\x0b\x45\x63hoRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message"(\n\x0c\x45\x63hoResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message"R\n\x0c\x45rrorRequest\x12\x1d\n\nerror_code\x18\x01 \x01(\tR\terrorCode\x12#\n\rerror_message\x18\x02 \x01(\tR\x0c\x65rrorMessage"\'\n\rErrorResponse\x12\x16\n\x06result\x18\x01 \x01(\tR\x06result")\n\rHeaderRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message"*\n\x0eHeaderResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message"+\n\x0f\x44ownloadRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message"H\n\x10\x44ownloadResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12\x1a\n\x08sequence\x18\x02 \x01(\x05R\x08sequence"E\n\rUploadRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12\x1a\n\x08sequence\x18\x02 \x01(\x05R\x08sequence"*\n\x0eUploadResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message"F\n\x0e\x43hatterRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12\x1a\n\x08sequence\x18\x02 \x01(\x05R\x08sequence"G\n\x0f\x43hatterResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12\x1a\n\x08sequence\x18\x02 \x01(\x05R\x08sequence2\xfe\x02\n\x0eTestingService\x12\x33\n\x04\x45\x63ho\x12\x14.testing.EchoRequest\x1a\x15.testing.EchoResponse\x12\x36\n\x05\x45rror\x12\x15.testing.ErrorRequest\x1a\x16.testing.ErrorResponse\x12=\n\nHeaderTest\x12\x16.testing.HeaderRequest\x1a\x17.testing.HeaderResponse\x12\x41\n\x08\x44ownload\x12\x18.testing.DownloadRequest\x1a\x19.testing.DownloadResponse0\x01\x12;\n\x06Upload\x12\x16.testing.UploadRequest\x1a\x17.testing.UploadResponse(\x01\x12@\n\x07\x43hatter\x12\x17.testing.ChatterRequest\x1a\x18.testing.ChatterResponse(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "testing_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ECHOREQUEST"]._serialized_start = 34
    _globals["_ECHOREQUEST"]._serialized_end = 73
    _globals["_ECHORESPONSE"]._serialized_start = 75
    _globals["_ECHORESPONSE"]._serialized_end = 115
    _globals["_ERRORREQUEST"]._serialized_start = 117
    _globals["_ERRORREQUEST"]._serialized_end = 199
    _globals["_ERRORRESPONSE"]._serialized_start = 201
    _globals["_ERRORRESPONSE"]._serialized_end = 240
    _globals["_HEADERREQUEST"]._serialized_start = 242
    _globals["_HEADERREQUEST"]._serialized_end = 283
    _globals["_HEADERRESPONSE"]._serialized_start = 285
    _globals["_HEADERRESPONSE"]._serialized_end = 327
    _globals["_DOWNLOADREQUEST"]._serialized_start = 329
    _globals["_DOWNLOADREQUEST"]._serialized_end = 372
    _globals["_DOWNLOADRESPONSE"]._serialized_start = 374
    _globals["_DOWNLOADRESPONSE"]._serialized_end = 446
    _globals["_UPLOADREQUEST"]._serialized_start = 448
    _globals["_UPLOADREQUEST"]._serialized_end = 517
    _globals["_UPLOADRESPONSE"]._serialized_start = 519
    _globals["_UPLOADRESPONSE"]._serialized_end = 561
    _globals["_CHATTERREQUEST"]._serialized_start = 563
    _globals["_CHATTERREQUEST"]._serialized_end = 633
    _globals["_CHATTERRESPONSE"]._serialized_start = 635
    _globals["_CHATTERRESPONSE"]._serialized_end = 706
    _globals["_TESTINGSERVICE"]._serialized_start = 709
    _globals["_TESTINGSERVICE"]._serialized_end = 1091
# @@protoc_insertion_point(module_scope)
