name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install 3.13.3

    - name: Install dependencies
      run: uv sync --group dev --all-extras

    - name: Run linting
      run: uv run just check

    - name: Run type checking
      run: uv run just mypy